[project]
name = "lab4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch>=8.19.1",
    "elasticsearch-dsl>=8.18.0",
    "ipykernel>=6.30.1",
    "requests>=2.32.5",
]
